### PR TITLE
Add more options to filter hln

### PR DESCRIPTION
**Pull request by ExcuseMi**
Hi, I've added the following options for filtering hln.be.

Verberg HLN+ artikelen;
Verberg HLN Shop;
Verberg footer;
Compacte modus;
Verberg reacties;

Quite happy with the compact mode because it removes most of the obvious empty spaces.

Note:
This is one of the instances where I started coding and forgot to check if something already existed. I don't  think there is a reason for 2 of these projects to exist.

### CODE REVIEW

**Comment by ExcuseMi** [comment]
@Drieze are you still maintaining this project?

**Comment by Drieze** [comment]
Hi @ExcuseMi, I will look into this asap. I'm still maintaining this project. Thanks for your effort and I'll keep you updated!

**Comment by Drieze** [comment]
Thanks for expanding this project @ExcuseMi ! Much appreciated! 👍

**Comment by ExcuseMi** [comment]
> Thanks for expanding this project @ExcuseMi ! Much appreciated! 👍

No problem.
You can build the zip, xpi files with ant.

Please update the id in the firefox specific manifest to whatever you see fit.
We need it for the chrome.storage.sync api.
https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/

**Pull request merged**
